name: 'Terraform Deploy'

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  ENV_DIR: envs/dev

jobs:
  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.0'

      - name: 'Terraform Init'
        run: terraform init
        working-directory: ${{ env.ENV_DIR }}

      - name: 'Terraform Plan'
        run: |
          terraform plan -out=tfplan \
          -var "name_prefix=${{ secrets.NAME_PREFIX }}" \
          -var "env=${{ secrets.ENV }}" \
          -var "location=${{ secrets.LOCATION }}" \
          -var 'vnet_address_space=${{ secrets.VNET_ADDRESS_SPACE }}' \
          -var 'subnet_address_space=${{ secrets.SUBNET_ADDRESS_SPACE }}' \
          -var 'default_tags=${{ secrets.DEFAULT_TAGS }}'
        working-directory: ${{ env.ENV_DIR }}
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: 'Terraform Apply'
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ env.ENV_DIR }}
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
